import type { Metadata } from 'next'
import { Inter, Righteous } from 'next/font/google'

import Navigation from '@/components/Header'
import Footer from '@/components/Footer'
import { ThemeProvider } from "@/components/theme-provider"

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FlexFit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider attribute='class'>
            <Navigation />
            {children}
            <Footer />
          </ThemeProvider>
        </body>
      </html>
  )
}
