import type { Metadata } from 'next'
import { Inter, Righteous } from 'next/font/google'

import Navigation from '@/components/Header'
import Footer from '@/components/Footer'
import { ThemeProvider } from "@/components/theme-provider"
import { QueryProvider } from '@/components/query-provider'
import { Toaster } from "@/components/ui/toaster";

import './globals.css'
import { Query } from '@tanstack/react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FlexFit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider attribute='class'>
            <QueryProvider>
              <Navigation />
              <Toaster />
              {children} 
              <Footer />
            </QueryProvider>
          </ThemeProvider>
        </body>
      </html>
  )
}
